version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "test-felipe"

phases:

  pre_build:
    commands:
        - echo hi

  build:
    commands:
        - echo "This is the root dir of my build"
        - pwd
        - pip list
        - virtualenv venv
        - . venv/bin/activate
        - ls -ltra
        - pip list
        - /bin/bash --rcfile /venv/bin/activate
        - pip install -r requirements.txt
        - pip list
        - echo "done!"

