version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "test-felipe"

phases:

  pre_build:
    commands:
        - echo hi

  build:
    commands:
        - pwd
        - ls -ltra
        - mkdir test
        - cd test
        - ls -ltra
