version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "test-felipe"

phases:

  pre_build:
    commands:
        - echo hi

  build:
    commands:
        - echo "This is the root dir of my build"
        - pwd
        - apt-get install -y source
        - virtualenv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - echo "done!"

